### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by TheGamingCupid** [ohitstom/spicetify-easyinstall#21]
Whenever I try to install spicetify it keeps on giving me an error on step 4 
![image](https://user-images.githubusercontent.com/93430607/159112180-5a089310-8993-4e02-bb43-dce657f43da7.png)

**Comment by ohitstom** [comment]
I'll update the timeout to be larger for the next update. This issue is often to do with your network speed, your country blocking certain scdn servers, or even just inconsistent internet connection.

Troubleshoot using a vpn to start with, if that doesnt help can you tell me your starting estimate time (in the image its 8:00) + a screenshot of a speetest from speedtest.net.

I'll attempt to remove timeouts altogether but this could actually be scdn terminating the connection as you have been downloading such a small file for so long.

**Comment by ohitstom** [comment]
Looks like the problem was solved.
